services:
  gateway:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      POSTGRES_SERVER: postgres
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - redis
      - minio
    ports:
      - "8000:8000"

  worker:
    build: .
    command: python -m app_worker.main
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379/0
      MINIO_ENDPOINT: minio:9000
      POSTGRES_SERVER: postgres
    volumes:
      - ./:/app
    depends_on:
      - redis
      - minio
      - postgres

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

volumes:
  pg_data:
  minio_data: